import type { Metadata } from "next";
import { EB_Garamond } from "next/font/google";
import "./globals.css";
import Providers from "./providers";

export const ebGaramond = EB_Garamond({ 
  subsets: ["latin"], weight: ["400", "500", "600", "700"] });

export const metadata: Metadata = {
  title: "DockerFresh-Seafood Delivery App in mumbai",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${ebGaramond.className} antialiased`}
      >
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
